### ISSUE TITLE
'PackageInfo' 'PackageStatus' Missing After Install

### ISSUE THREAD

**Issue by Snow-Okami** [Unity-Technologies/AutoLOD#100]
After trying to install this plugin I am getting multiple errors across the files. The two repeating errors are:

```
Library\PackageCache\com.unity.autolod@9492bc0620\Editor\AutoLOD.cs(184,13): error CS0246: The type or namespace name 'PackageStatus' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.autolod@9492bc0620\Editor\AutoLOD.cs(191,42): error CS1061: 'PackageInfo' does not contain a definition for 'status' and no accessible extension method 'status' accepting a first argument of type 'PackageInfo' could be found (are you missing a using directive or an assembly reference?)

```
Any idea how to resolve this? I can find some documentation on this but it seems this is a Unity 6 feature only. I am using 2023. Was this updated for that and there's no backwards compatibility?

**Comment by amirebrahimi** [comment]
See #98. It's likely you'll have to get this through a fork.

**Comment by Snow-Okami** [comment]
Thank you very much! I was able to solve it by using the source and editing it. But I will try one of these newer updated forks, I did not know they existed.
