### ISSUE TITLE
Use a polygon budget instead of quality percentage for reducing LODs

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#11]
in hierarchy added a lodgroup with 3 lods to a cliff
reimported the cliff asset
in hierarchy added another lodgroup with 3 lods to a house
reimported the house
now simplygon keeps spawning jobs
https://i.imgur.com/f9GF3MP.png

**Comment by laurentopia** [comment]
on second thought, I think the way poly reduction is evaluated is causing problems: because each mesh's job is independent, there is no reference to the total % poly budget so a small polycount but important sphere will get decimated to a tetrahedron within LOD1 instead of remaining a sphere and eating polys elsewhere.
so there need to be an option to keep the meshes' in one job and let simplygon figure out budget like a big boy

**Comment by amirebrahimi** [comment]
How were you generating these LODs? It sounds like you are using the menu item to generate them?

**Comment by amirebrahimi** [comment]
And I'm not able to follow your example about total % poly budget. The quality is based on absolute quality from LOD0, so 0.5 is half the quality of that. The system isn't based on a poly count budget.

**Comment by amirebrahimi** [comment]
I took the liberty to rename this issue and mark it as a feature-request, since what you originally reported as bug was not actually the case.

**Comment by laurentopia** [comment]
yeah don't worry about that poly budget thing, that's what it does, sorta
