### ISSUE TITLE
autoLOD vs LODGroup?

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#14]
Once the meshes are baked, what's the difference?
when I dolly in and out in the scene view I notice a hiccup, is this LODGroup trademark ? I mean 5.3 shader prewarm got much better and was no longer needed plus all the lods share the same material...

**Comment by amirebrahimi** [comment]
AutoLOD is hierarchical LOD, so the meshes are baked at different volume structures. This is different than traditional LODGroups, which may bake everything of a specific type if static batching is turned on. The benefit for AutoLOD is that different types of meshes are baked together with a certain bounding volume.

It's hard to asses what your issues are without more information. Getting access to a project and/or screenshots would help.

Based on the current implementation there may be hiccups when dollying in, but dollying out should not cause a hiccup.

**Comment by laurentopia** [comment]
I can give you collab access to the project, what's your email?

**Comment by amirebrahimi** [comment]
Sure. It's amir @ unity3d.com
