### ISSUE TITLE
how does autoLOD determines the LOD chain %?

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#15]
Simplygon can do decimation based on pixel size, so in theory it's possible to extract that from the LODGroup % but I don't think that's what's happening.

**Comment by amirebrahimi** [comment]
Currently, the percentages are [fixed](https://github.com/Unity-Technologies/AutoLOD/blob/743c4d1e8fc28b6fdd2739fe6fbf7f7e0b14c3b4/Scripts/Editor/ModelImporterLODGenerator.cs#L246) based on the LOD level (e.g. LOD1 is 50%, LOD2 is 25%). It'd be better to have these match more closely to what pixel size the LOD was generated at, but I'm not sure all simplifiers would support that.

**Comment by laurentopia** [comment]
How do decimators that support this do the math?

**Comment by amirebrahimi** [comment]
Not entirely sure, but essentially you're wanting a screen percentage that minimizes the error between the previous LOD and the current LOD at a specific distance away from the camera. Off the top of my head I could see approaching this one of two ways:

1. You could produce a LOD with some poly percentage of the previous and then determine the correct screen percentage to switch it at
2. You could decide the screen percentage you want and iteratively determine what poly percentage converges on that
