### ISSUE TITLE
unable to remove LOD in 2017.3

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#16]
```
Destroying assets is not permitted to avoid data loss.
If you really want to remove an asset use DestroyImmediate (theObject, true);
UnityEditor.Experimental.AutoLOD.AutoLOD:RemoveLODs(MenuCommand)

```

**Comment by laurentopia** [comment]
only way to remove lod seems to be removing autoLOD and reimporting

**Comment by amirebrahimi** [comment]
The menu command you are using is only for prefabs or GameObject in the scene.

For assets on disk, you can disable LOD generation under `Edit -> Preferences... -> AutoLOD` and then you can reimport whatever assets you wish. If you simply want to disable LOD generation for a single file, you can go into the <asset name>_lods.asset and toggle "Override Defaults" to de-select "Generate on Import"

**Comment by laurentopia** [comment]
Thanks, that solves it.
