### ISSUE TITLE
Instant Meshs Support

### ISSUE THREAD

**Issue by Ziboo** [Unity-Technologies/AutoLOD#2]
Hi,

Is it possible to integrate InstantMesh Support ?
It's free :)

https://github.com/wjakob/instant-meshes

**Comment by HeadClot** [comment]
Instant meshes is for retopo work more than LOD work.

**Comment by laurentopia** [comment]
Instant Mesh is a good suggestion as it produces the cleanest decimated mesh but unfortunately it doesn't transfer UVs, so it would requires quite some tinkering on the part of the unity team.

**Comment by amirebrahimi** [comment]
I took a look at this and tried using CLangSharpPInvokeGenerator from https://github.com/microsoft/ClangSharp, but it didn't work immediately and looks like it would require a lot more work.

It's possible to launch a process to simplify each mesh, but that isn't ideal and would require compilation of instantmesh for each platform and distribution, which is not maintainable. It's possible to set up a pipeline to build that on the user's machine, but then those tools would be required by the dev.

So, overall, the best situation would be where someone ports instantmesh to C# code and/or publishes libraries for each platform w/ C# wrappers and that can get used here in AutoLOD.
