### ISSUE TITLE
getting holes in mesh

### ISSUE THREAD

**Issue by friuns2** [Unity-Technologies/AutoLOD#25]
![image](https://user-images.githubusercontent.com/16543239/38905571-38eee1ce-42ba-11e8-927d-60769566774f.png)

tried both simulated and quadratic simplification

**Comment by laurentopia** [comment]
It's a limitation in the decimator when handling UV discontinuities.
The decimator has been fixed a month ago but not integrated in autolod yet.

**Comment by friuns2** [comment]
where can i check out decimator?

**Comment by amirebrahimi** [comment]
Apologies all. Will be getting to the backlog of AutoLOD issues soon. I'm a single dev working on another project primarily while trying to maintain this in my "free time".

**Comment by amirebrahimi** [comment]
This should be fixed with the update to UnityMeshSimplifier in #6. Grab latest and if it doesn't fix your problem, then re-open this issue.
