### ISSUE TITLE
lods generated rotated

### ISSUE THREAD

**Issue by friuns2** [Unity-Technologies/AutoLOD#26]
lods generated rotated

![image](https://user-images.githubusercontent.com/16543239/39323939-c9626ba8-4996-11e8-8993-a05c0312ada4.png)

[sniperscope.zip](https://github.com/Unity-Technologies/AutoLOD/files/1952437/sniperscope.zip)

**Comment by amirebrahimi** [comment]
What simplifier were you using?

**Comment by friuns2** [comment]
QuadricMeshSimplifier

**Comment by amirebrahimi** [comment]
And which revision of AutoLOD are you using? I just recently updated that simplifier submodule.

**Comment by friuns2** [comment]
"Skip generating if not overriding and globally "generate on import" is disabled"

**Comment by MattOstgard** [comment]
Same issue for me using latest (062ae527f99f5e5104c63f4ea5fc4900a0b1949a) and exporting from 3ds max.

**Comment by NumT** [comment]
Same issue here from 3ds Max.
