### ISSUE TITLE
Really unable to test it out

### ISSUE THREAD

**Issue by JohnW1916** [Unity-Technologies/AutoLOD#3]
It sounds like a fantastic project, but it doesnt matter what objects I import or how simple they are, the editor crashes as soon as it starts the simplification/lod generation  process.

Is there any important thing im missing out ?
Using unity 2018.1.0b2

UPDATE.
Downgraded to 2017.3 , it doesnt crash anymore, but, one it generates unusable meshes, and second, the meshes wont show in the scene anyway. 
I guess this is "very experimental". 

UPDATE 2.
It seems like some simplygon 3rd party software/plugin is required in order for this to work.

**Comment by Noa3** [comment]
how did you get the simplygon plugin? i have the sdk but the plugin dont show up for download :/

**Comment by JohnW1916** [comment]
I didnt get the plugin ... I just realized its required so I quit testing this. The built in solution is nowhere usable. I guess we would have to..wait.

**Comment by Noa3** [comment]
awww thx for the awnser. maybe it comes support for AutomaticLOD from asset store

**Comment by amirebrahimi** [comment]
@JohnW1916 - I'll have to try this out on 2018.1 to see why it is crashing.

@Noa3 / @JohnW1916 - You need to register with Simplygon / Microsoft to get access to Simplygon Connect (which is their free version). However, I just checked the site and it seems that they have pulled their Unity plugin. I'm not sure why as the 5.5 plugin was working for 2017.3. There are also hooks for InstaLOD though if you want to get an evaluation version of that.

**Comment by amirebrahimi** [comment]
FYI: I just pushed a change that supports https://github.com/Whinarn/MeshDecimator if you want to give that a shot.

**Comment by amirebrahimi** [comment]
@JohnW1916 - I tested this out with 2018.1.0b2 and here were my results:

1. It crashed initially on creating an empty project (no AutoLOD added yet)
2. I cloned AutoLOD from github and despite a few warnings it seemed to import correctly
3. I copied a folder of a teddy model with textures in and it imported without crashing, but it also left Unity in a weird state where the project window did not update.
4. I then tried reimporting the teddy model and it did crash (call stack showed that it was on setting the mesh name)
5. Tried it again and it consistently crashes in the same place
6. If I comment out `mesh.name = name` in [WorkingMesh.cs](https://github.com/Unity-Technologies/AutoLOD/blob/master/Scripts/Helpers/WorkingMesh.cs#L136), then it works without crashing. You could make this change in your own code if you want to get it working on 2018.

In the meantime, I'll submit a bug report.

**Comment by amirebrahimi** [comment]
Nevermind, there was a quick fix for the bug, which is when a mesh.name is set to null.
Fix is on master now: https://github.com/Unity-Technologies/AutoLOD/commit/884a40e174634d5924d46a47ff989083194b0559
