### ISSUE TITLE
Skinned meshes and LOD

### ISSUE THREAD

**Issue by twobob** [Unity-Technologies/AutoLOD#31]
Are they supposed to work?

Nothing happens seemingly when right clicked.

latest version

**Comment by amirebrahimi** [comment]
No, skinned meshes are not currently supported.

**Comment by twobob** [comment]
Some sort of warning in the UI would be trivial to implement. Thinking of the general populus then

**Comment by amirebrahimi** [comment]
@twobob - Added in 1f2c171
