### ISSUE TITLE
Generalised support for 3rd party simplification solutions

### ISSUE THREAD

**Issue by twobob** [Unity-Technologies/AutoLOD#32]
might it be possible to at-some-point think about linking/reaching out to some time-served battle-tested UAS solutions and making sure they know about the project?  It would seem to be in Unity ecosphere's ethos and gives them every chance to get involved.
https://assetstore.unity.com/packages/tools/modeling/simple-lod-25366
https://assetstore.unity.com/packages/tools/quicklod-optimization-framework-16514
For examples...
: )

**Comment by amirebrahimi** [comment]
My hope with releasing AutoLOD as open source was that other devs could plug their simplifiers into the system or at least write hooks for their asset store packages. I'm not sure if everyone reads the blog, so perhaps the authors were unaware. Also, the project is experimental, so it's not necessarily what would actually make it into the final product. I'll try reaching out to the authors you mentioned to see if they have any interest.

**Comment by chillersanim** [comment]
Hello, I am the creator of QuickLod, thank you for writing me.
Your project looks very interesting!
Can you elaborate what kind of features you want to use/integrate or what kind of hooks/API you are looking for?

@twobob 
Thank you for referencing my asset. :)

**Comment by twobob** [comment]
@chillersanim  Very simply if one looks at the implementations currently extant for example https://github.com/Unity-Technologies/AutoLOD/blob/master/Scripts/Editor/MeshSimplifiers/MeshDecimatorSimplifier.cs
that is the entire implementation required to get your "Simplifier" included

**Comment by amirebrahimi** [comment]
Well, I'll leave it to @twobob to expand on what he might want from QuickLod.

However, the purpose of AutoLOD was simply to provide a framework to allow other LOD simplifiers to plug in easily. There's a default simplifier that shows how integration is done, but I'd be happy to support you if you think you want to add hooks for QuickLod. Currently, only non-skinned meshes are supported.

**Comment by twobob** [comment]
All I want is for it to hook into his optimisers, just like the other implementations
