### ISSUE TITLE
Compiler error in Unity 2017

### ISSUE THREAD

**Issue by kevinfoley** [Unity-Technologies/AutoLOD#34]
Line 808 of `LODVolume` is this:

    var prefab = PrefabUtility.GetCorrespondingObjectFromSource(go);

This requires Unity 2018, but you don't have a corresponding compiler directive. You'll need to change this like you did in `AutoLOD`:

    #if UNITY_2018_2_OR_NEWER
                    var prefab = PrefabUtility.GetCorrespondingObjectFromSource(go);
    #else
                    var prefab = PrefabUtility.GetPrefabParent(go);
    #endif

**Comment by amirebrahimi** [comment]
Fixed with 7f51dea
Happy to take PRs from you in the future if that is easier.
