### ISSUE TITLE
Limited number of objects possible to process at once with Simplygon

### ISSUE THREAD

**Issue by Keeetrab** [Unity-Technologies/AutoLOD#38]
Hey, Once I select more than ~15 objects to process at once, simplygon plugin stops. Jobs are posted one by one I guess so why this happens. Any solution to automate it?

**Comment by JangkyuSeo** [comment]
I fixed the same problem.
It seems like making too many threads.  
When you using Simplygon, you should managing thread count to not making too many threads.
My opinion is make thread pool and use it.

**Comment by Keeetrab** [comment]
I m using 2.5.1 version of Unity plugin and 8.2.359 Simplygon Lib.

I tried to count workers

                        var worker = new BackgroundWorker();            
                        workersWorking++;

and on worker.RunWorkerCompleted  I substract workersWorking. Then I tried to check how many workers are in GenerateLODsCoroutine()

            var go = menuCommand.context as GameObject;
            if (go)
            {                              
                while(workersWorking > 2)
                {
                    yield return null;
                }
                GenerateLODs(go);
               
            }

However this, blocks whole Unity. Any tips how should I approach it?

**Comment by JangkyuSeo** [comment]
You should use **yield return WaitForSecond(time)** insted of **yield return null.**

Because TimedEnumerator is not stopped until pass the iteration time.
It means that return null is not continue next frame. It will continue same frame.
