### ISSUE TITLE
Build for artists?

### ISSUE THREAD

**Issue by WinExploder** [Unity-Technologies/AutoLOD#40]
Hello,
I'm an artist and I don't know how to use the git functions that are required to install this plugin. It'd be really cool if you guys could upload a unitypackage for people like me!

**Comment by amirebrahimi** [comment]
Here's a unity package at the current revision 84a096e:
[AutoLOD-84a096e.zip](https://github.com/Unity-Technologies/AutoLOD/files/2355093/AutoLOD-84a096e.zip)

It's fairly easy to use git and is only a one liner, so I encourage you to give it a shot some time!
https://github.com/Unity-Technologies/AutoLOD#cloning
