### ISSUE TITLE
Demo Please!

### ISSUE THREAD

**Issue by lic1227** [Unity-Technologies/AutoLOD#41]
Demo Please! Dont Know How to use Scene LOD at all.

**Comment by murphysurveys** [comment]
From what I have read in the issues threads, a good demo might involve:

1. scenes using one of each of the apparently required LoD generators: Simplygon, InstaLoD, and Mesh Decimator.
2. a standard model such as the Stanford Dragon.
3. basic FlyCamera controls attached to the camera.

**Comment by tranduc2211** [comment]
Can someone explain how can I use sceneLOD. Does it auto-generated when I create a new subscene? Sorry I'm pretty new and dont know how to use this tool

**Comment by lijualivenow** [comment]
> From what I have read in the issues threads, a good demo might involve:
> 
> 1. scenes using one of each of the apparently required LoD generators: Simplygon, InstaLoD, and Mesh Decimator.
> 2. a standard model such as the Stanford Dragon.
> 3. basic FlyCamera controls attached to the camera.

do you have demo for Mesh Decimator.

**Comment by amirebrahimi** [comment]
Added a video link in: c524dcf
https://youtu.be/EuBeZvzVwrw
