### ISSUE TITLE
Packages didn't download?

### ISSUE THREAD

**Issue by Cinabutts** [Unity-Technologies/AutoLOD#42]
The packages didn't download, I got the folders: Packages, Packages/CCU and Packages/UnityMeshSimplifier.
But it didn't include the contents only the meta files. I can manually fix this i'm sure but it'd be nice not to have to. If this is a Github related issue like I assume when you download the zip it doesn't include submodules than that's understandable but either way you should say that somewhere if not fix it. Loving this idea though so far.

**Comment by amirebrahimi** [comment]
You have to clone with the `--recursive` option:
https://github.com/Unity-Technologies/AutoLOD#cloning
