### ISSUE TITLE
Editor script does nothing, any errors silent

### ISSUE THREAD

**Issue by thePostFuturist** [Unity-Technologies/AutoLOD#43]
I tried selecting a model with skinned mesh renderers either as a prefab in the Assets directory, or as a game object in the scene with absolutely nothing happening when running the editor script.

No errors.

Using 2018.2.5f1

**Comment by thePostFuturist** [comment]
Got a log upon import that SkinnedMeshRenderers are unsupported. Closing.

**Comment by amirebrahimi** [comment]
Do you mean in the README.MD or is there somewhere else you were looking to see that?
