### ISSUE TITLE
Random resize bug Blender models

### ISSUE THREAD

**Issue by LoneDev6** [Unity-Technologies/AutoLOD#46]
Hello, I think I found a bug: lods scale appears to be broken if the original object has a scale not equal to (1, 1, 1) when imported.
For example:
I have a road model scaled in Blender to (0.096, 0.45, 0.45), if I import it with the AutoLOD enabled the generated lods have a strange size:

![lod0](https://user-images.githubusercontent.com/27242001/46099215-7d058800-c1c6-11e8-91be-13e871443d12.png)

![lod1](https://user-images.githubusercontent.com/27242001/46099222-81ca3c00-c1c6-11e8-82f4-cfbe8c6df203.png)

Let me know if I made any mistake or if it's a real bug, thanks! 😄

**Comment by amirebrahimi** [comment]
Hi, Thanks for the PR! Can you send me a copy of the asset, so I can repro?

**Comment by amirebrahimi** [comment]
I was able to create a test in Blender. This has been merged now.
