### ISSUE TITLE
Exceptions on generating LODs

### ISSUE THREAD

**Issue by SebastianBaumgartner** [Unity-Technologies/AutoLOD#49]
Hello,

the AutoLOD project looks very promising!!
I just added it to my actual project.
If i try to generate LODs of an fbx file in the Editor i get the following exceptions:
 
> ArgumentException: array.Length (15) does not match the Length of this instance (14).

> A Native Collection has not been disposed, resulting in a memory leak. It was allocated at V:\AREC\AUS\trunk\AUS\Assets\AutoLOD\Scripts\Helpers\WorkingMesh.cs:472.

Any suggestions whats the reason??
Unity 2018.3.0f1

thanks, sebastian

**Comment by amirebrahimi** [comment]
You must have hit an edge case with the recent changes I made to support the job system. Any chance you could provide the fbx file here or via email (amir at unity3d.com)?
