### ISSUE TITLE
Impossible to import

### ISSUE THREAD

**Issue by Gui205** [Unity-Technologies/AutoLOD#5]
Tryed with Simplygon 2.5.1 for Unity side and SimplygonSDK 8.2.317.5902 for Window 10 side. 

Actual statut : Crash of Unity when importing mesh. 

[https://image.noelshack.com/fichiers/2018/04/2/1516701127-image.png](url)

But as you can see, i think the problem come from the Simplygon side, if someone have an idea ?

**Comment by amirebrahimi** [comment]
If you are unable to resolve what you are encountering, then please provide some more info.

**Comment by Gui205** [comment]
I update my statut :)

**Comment by amirebrahimi** [comment]
Hmm... Did you change any of the default settings for Simplygon?
Also, does this happen on all meshes?

FYI: I just pushed a change that supports https://github.com/Whinarn/MeshDecimator if you want to give that a shot.

**Comment by Gui205** [comment]
Mmmh, i think my  problem come from Simplygon, i try to create my LOD directly by Simplygon and get the some error. 

I need to take a look on this side but Simplygon dont have Unity support at all so it's difficult to solve my issue

**Comment by Gui205** [comment]
Okay, problem with Simplygon has been fixed ( Just delete the Library folder for foce to recompile all seem to be ok ). 

I executed all my test with your last distribution on GitHub and now work good but 2 importants point : 

- With your actual system we need to import mesh with material already asign, otherwise the LOD calculation was apply with defaut Front material, and it's impossible to compute with another material later on the LOD1 and higher.
- Sometime the pivot point on LOD1 and higher was different of LOD0 and that impact the visible result of the fade between LOD0 and LOD1 : 

[https://image.noelshack.com/fichiers/2018/04/3/1516824310-pivot-01.png](url)

[https://image.noelshack.com/fichiers/2018/04/3/1516823860-pivot-02.png](url)

**Comment by amirebrahimi** [comment]
I'd need to try and reproduce this with the model you have. Could you make that available? If you need to send to me privately, then you can email me at amir at unity3d.com.

**Comment by Gui205** [comment]
- Last biggest point i dont know how to describe this one so i show some screen of the problem : 
LOD0
https://image.noelshack.com/fichiers/2018/04/3/1516824828-lod0.png
LOD1
https://image.noelshack.com/fichiers/2018/04/3/1516824843-lod1.png

**Comment by amirebrahimi** [comment]
Looks like it is using the SimulatedMeshSimplifier. Can you check under the preferences?

**Comment by Gui205** [comment]
Model ( Not really optimized :S )  : 
https://mega.nz/#!kpkyADwQ!X1gmOGaqria6RMHbsWoaHGjL0p9SMIrJLoc48j6ZTjs

Entire project : 

https://mega.nz/#!Bkk3WQSb!HaI0O1UIOzHxSjhI5AaimMPUb4Gc_oHwQZCOeeTbk_E

**Comment by Gui205** [comment]
Yes he use the SimulatedMeshSimplifier.

**Comment by amirebrahimi** [comment]
I thought you were using Simplygon?

**Comment by Gui205** [comment]
On your first revision yes, but since i use your last rev i dont have the Simplygon option in my option

**Comment by amirebrahimi** [comment]
Well, SimulatedMeshSimplifier is not a real simplifier. See #4 for more info.
AutoLOD should have re-enabled Simplygon support after you reimported unless you removed the Simplygon package.

**Comment by Gui205** [comment]
Mmmh strange i re-import all but still not have Simplygon option ( I share you my entire project maybe you could look by yourself my issu )

**Comment by amirebrahimi** [comment]
I tried to reproduce your problem with the pivot point, but don't see it happen. I tried with both the SimulatedMeshSimplifier and the new MeshDecimatorSimplifier.

![model_lods](https://user-images.githubusercontent.com/904110/35367016-0a3f3dd0-0131-11e8-82cc-3ff09ea49957.gif)

I notice that you made an edit to your original post and added that this problem only occurs when HLOD is active. It's possible that you were able to get SceneLOD/HLOD into a state where you moved the original object and it didn't rebuild. You can always delete the HLOD and LodVolumeNode GameObjects to have it regenerate.

Re: your other point about the material not importing -- that is not a problem with AutoLOD and is likely an issue with your model file because when I imported your model it came in without any textures. You would need to fix that in the authoring package that you used to create the model.

FYI: Many of your image links are broken. GitHub supports dragging and dropping images directly in the comment window, so I suggest you do that in the future.

**Comment by amirebrahimi** [comment]
I took a look at your project and it looks like you didn't clone AutoLOD into the correct directory as the README states. Your project folder should look like this:

![image](https://user-images.githubusercontent.com/904110/35367399-feb51424-0132-11e8-92ba-535b77c080d1.png)

Also, you're missing the CCU submodule, which would be there if cloned properly. That is why Simplygon isn't showing up. I'd suggest you follow this part of the README:
https://github.com/Unity-Technologies/AutoLOD#cloning

**Comment by Gui205** [comment]
I'm glad to tell you everything works good now ! I'm clone your repository, and redownload the Simplygon Asset directly by the asset store, and now everything work perfectly and really smooth. 

GREAT JOB GUYS !

**Comment by amirebrahimi** [comment]
Thank you. I'm glad you sorted things out.
