### ISSUE TITLE
Unusable output

### ISSUE THREAD

**Issue by soraryu** [Unity-Technologies/AutoLOD#50]
I was really excited to find this. But unfortunately the first try is giving me really really bad results (much worse than expected). Basically just garbage with slight resemblance of the original contours.

Are there any options I can play with?

![unity_2019-02-22_14-15-43](https://user-images.githubusercontent.com/2693840/53245925-82043000-36af-11e9-9fdd-2cf059692ff7.jpg)
![unity_2019-02-22_14-15-38](https://user-images.githubusercontent.com/2693840/53245926-82043000-36af-11e9-8715-321d6d5d98d5.jpg)

For comparison, here's an optimization to 3% using ProOptimizer in 3ds max:
![3dsmax_2019-02-22_14-34-30](https://user-images.githubusercontent.com/2693840/53245953-96e0c380-36af-11e9-9869-012d315ba85b.jpg)

**Comment by amirebrahimi** [comment]
Hmm..This looks like a bug. Can you look at your AutoLOD preferences under Edit->Settings and let me know what the default simplifier is set to?

**Comment by amirebrahimi** [comment]
Hi @soraryu - can you provide me with the model and/or let me know if you are using the `SimulatedMeshSimplifier`?

**Comment by soraryu** [comment]
Can you give me your mail address? I can't share it publicly.

**Comment by amirebrahimi** [comment]
amir at unity3d dot com

**Comment by amirebrahimi** [comment]
Hi @soraryu - I've corresponded with you off-site and haven't heard back, so I'm going to close this issue. You're welcome to re-open it if need be.
