### ISSUE TITLE
Assembly has reference to non-existent assembly 'UnityMeshSimplifier' 

### ISSUE THREAD

**Issue by abosaqer** [Unity-Technologies/AutoLOD#52]
When I import it to my project 

This error appears::
Assembly has reference to non-existent assembly 'UnityMeshSimplifier' (Assets/AutoLOD-master/Scripts/Editor/_AutoLOD-Editor.asmdef)

My Unity3d version : 2017.3.1f1

Is there any solution?

**Comment by amirebrahimi** [comment]
Sounds like you need to pull submodules. You should have cloned with the following command:
`git lfs clone --recursive https://github.com/Unity-Technologies/AutoLOD`

If you've already pulled, then you can use [repo-rinse](https://gist.github.com/nicktoumpelis/11214362).
