### ISSUE TITLE
Memory Leak Errors: Possible Extension of Issue #49

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/AutoLOD#53]
# Problem:
Memory leak warnings produced during creation of LODs post import of model. Problem occurs on models of several different types including .fbx, .blend, and .obj. The warnings indicate possible memory leaks, and if an error occurs, error indicates that they are produced from the memory leak. 

# Engines Attempted:
2019.1.02f, 2018.3.13f, 2018.3.08f

# Changes Tried:
Max Exec Time 8, 15
Both Mesh Simplifies
Both Default Batchers
Max LOD Gen 3, 4 and 5
Initial LOD Max Poly 5000000, 50000000, 50000000

# Additional Notes:
Model Max Poly: 190000
The error seems to occur on larger/more complex meshes that use only a few different sections/subsections as compared to a model that is broken into several sections/subsections

**Comment by iswire2016** [comment]
I'm pretty sure that it is a confirmed memory leak. Warnings kept appearing every second. I restarted unity and the warnings about a potential memory leak went away. The continuous leak occurs after successfully creating a LOD after a fail creation occurred.

**Comment by amirebrahimi** [comment]
Fixed in cdc00f8, but unfortunately warnings still show in 2018.4.8f1, which is not likely to change.
Unity 2019.1.14f1 or later is recommended
