### ISSUE TITLE
Wrong normals

### ISSUE THREAD

**Issue by Spy-Shifty** [Unity-Technologies/AutoLOD#54]
Model made with blender!
![image](https://user-images.githubusercontent.com/18166769/58721479-5cd13d00-83d5-11e9-8b08-0048ef5068c9.png)

![image](https://user-images.githubusercontent.com/18166769/58721491-622e8780-83d5-11e9-9df0-b9ddda67803b.png)

![image](https://user-images.githubusercontent.com/18166769/58721504-678bd200-83d5-11e9-8877-ebbf1ad340ff.png)

**Comment by Pelmog** [comment]
Yeah, I get this 'similar' look using Unity 2019.1.2, with the LWRP and some simple Synty low poly assets. :(

**Comment by Spy-Shifty** [comment]
Well, under settings you can change the algorithm to Fast Quadric Mesh Simplification

This gives you a slightly better result. But it's not optimal...
You have to load the github submodul to see the algorithm in the settings.
 (https://github.com/Unity-Technologies/AutoLOD/tree/master/Packages)

**Comment by amirebrahimi** [comment]
@Spy-Shifty is correct - you need to clone w/ submodules otherwise it will default to the "simulated mesh simplifier" which simply punches holes in your mesh. I'll probably remove this in the near future or show some kind of warning.

https://github.com/Unity-Technologies/AutoLOD#cloning
