### ISSUE TITLE
AutoLOD generated mesh smoothing, how to disable?

### ISSUE THREAD

**Issue by DevAkseli** [Unity-Technologies/AutoLOD#55]
Hi, trying to use AutoLOD with lowpoly project, but generating mesh with the default QuadricMeshSimplifier results in smoothed mesh. I spent hours trying to learn the code and trying to pinpoint the exact part where the smoothing feature is done, but couldnt find it. 

Removing these files from the QuadricMeshSimplifier script results in sharp mesh, but all the colors of the model are lost.
 meshSimplifier.UV1 = inputMesh.uv;
outputMesh.uv = meshSimplifier.UV1;

Hope that helps to solve the problem!

**Comment by amirebrahimi** [comment]
Do you have an example model you can provide?

Also, did you try adjusting your smoothing settings in the model importer settings?
![image](https://user-images.githubusercontent.com/904110/64052727-7ac54f80-cb34-11e9-9833-07924d6ced94.png)

Try grabbing latest, too, which has an update to the MeshSimplifier, which is maintained at https://github.com/Whinarn/UnityMeshSimplifier

**Comment by amirebrahimi** [comment]
Closing this issue because it has gone stale. Hopefully my last response was helpful.
