### ISSUE TITLE
Failing to add LoD in basic scene when inputting to LoD Volume script

### ISSUE THREAD

**Issue by murphysurveys** [Unity-Technologies/AutoLOD#56]
A LoD group of 5 levels was generated from Simplygon on local grid.
The resulting prefabs were copied into a basic scene.
The LoD Group prefab was attached to the HLoD Root public input of the Volume Script which is attached to the automatically added LODVolumeNode0 object.
The "Enable HLOD" button was clicked.

No geometry renders during play in the editor, with a basic FlyCamera moving in the scene.

I'm not sure if the LoD prefabs were connected to the AutoLoD system in the correct way, by attaching the group prefab to the HLoD root.

![AutoLoDTest](https://user-images.githubusercontent.com/49417156/64953337-7ca04a00-d87a-11e9-9e73-32bccf10a98b.png)

**Comment by amirebrahimi** [comment]
Hi @murphysurveys - If you select "Disable HLOD" do the models show up? Sometimes when first enabling HLOD it takes a moment for the LODs to get generated. Would you be able to share the project with me?

**Comment by amirebrahimi** [comment]
Ahh, I see what you are doing now. I don't think it will work if you try to provide your own HLOD root by assigning it. Please see this video for a how-to: https://youtu.be/EuBeZvzVwrw
