### ISSUE TITLE
Clarification needed: AutoLOD vs. UnityMeshSimplifier

### ISSUE THREAD

**Issue by soraryu** [Unity-Technologies/AutoLOD#58]
If I get that right, UnityMeshSimplifier is the thing actually generating the LODs, and AutoLOD is "mostly" an AssetPostprocessor doing that on import? Can you clarify what the scope of these solutions is?

**Comment by amirebrahimi** [comment]
Yes, that is correct. In addition, AutoLOD also includes SceneLOD, which is an HLOD implementation for chunking scenes into hierarchical LODs.

**Comment by soraryu** [comment]
@amirebrahimi would be great if you can add it to the Readme, as it's not clear right now!

**Comment by amirebrahimi** [comment]
Done: https://github.com/Unity-Technologies/AutoLOD/commit/c2b418f89a0c2f6139f7114fe33e276ed1a42ad4
