### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by diybl** [Unity-Technologies/AutoLOD#59]
NullReferenceException: Object reference not set to an instance of an object
Unity.AutoLOD.AutoLOD.UpdateDependencies () (at Assets/AutoLOD/Scripts/Editor/AutoLOD.cs:182)
Unity.AutoLOD.AutoLOD..cctor () (at Assets/AutoLOD/Scripts/Editor/AutoLOD.cs:215)
Rethrow as TypeInitializationException: The type initializer for 'Unity.AutoLOD.AutoLOD' threw an exception.

**Comment by VoidCallerZ** [comment]
We're having this problem aswell

**Comment by amirebrahimi** [comment]
You must check what simplifier you have set under Edit -> Preferences for AutoLOD. If none are present, then it likely means you have pulled this project into your repo without the required submodules.

See: https://github.com/Unity-Technologies/AutoLOD#cloning

I've added a new warning with 8842c1f
