### ISSUE TITLE
Editor button conflicts with Pro Grids

### ISSUE THREAD

**Issue by amarillo-sebas** [Unity-Technologies/AutoLOD#60]
![image](https://user-images.githubusercontent.com/5789040/65931938-4235c180-e3d1-11e9-876e-94dadd36f54a.png)

As you can see in the image, the button AutoLOD puts in the scene viewport overlaps the Pro Grids (an official Unity asset). The Pro Grids button is unusable.

**Comment by amarillo-sebas** [comment]
Is there a way to disable that button?

**Comment by amirebrahimi** [comment]
You can disable it by turning off SceneLOD in Edit -> Preferences... -> AutoLOD
![image](https://user-images.githubusercontent.com/904110/66082385-e2e5c780-e51e-11e9-8e75-ea3ee625fcf2.png)
