### ISSUE TITLE
Limited Information 

### ISSUE THREAD

**Issue by lijualivenow** [Unity-Technologies/AutoLOD#61]
Current document is limited, do you have any video tutorial or step by step approach. It will be helpful. 

The old version is working in 2019.2.7f but the new version.

Thank you.

**Comment by ralofpatel** [comment]
Yes. There is no information or guidelines about how to setup Auto LOD and how to use it.

**Comment by amirebrahimi** [comment]
Duplicate of #41, which has been resolved.
https://youtu.be/EuBeZvzVwrw
