### ISSUE TITLE
AutoLOD setup problem

### ISSUE THREAD

**Issue by AzatKhafizov** [Unity-Technologies/AutoLOD#63]
Hi!
I try to test AutoLOD.
But unfortunately when I create Unity project and then use "git lfs clone --recursive https://github.com/Unity-Technologies/AutoLOD", I got next errors

Could you help me, please? What should I do?

**Comment by AzatKhafizov** [comment]
![image](https://user-images.githubusercontent.com/1913784/72894834-3037b000-3d2d-11ea-88c6-89e3fabe6726.png)

**Comment by AzatKhafizov** [comment]
![image](https://user-images.githubusercontent.com/1913784/72894874-4c3b5180-3d2d-11ea-80ab-a449b7d5400f.png)
This is how Preferences/AutoLOD window looks like

**Comment by amirebrahimi** [comment]
It looks like your pull did not include submodules. Can you try a fresh pull and let me know if you see any errors? You should have files in the AutoLOD/Packages/UnityMeshSimplifier folder.

**Comment by AzatKhafizov** [comment]
amirebrahimi, hi!
I repeated everything from scratch. And I got this problem again.
Here are my steps in details:
1. I create new Unity project (I am not using Git for this. It is just new Unity project)
2. I am launching CMD and moving to Assets folder of this project via console commands
3. When I am at Assets folder of this project I am launching next command: "git lfs clone --recursive https://github.com/Unity-Technologies/AutoLOD"
The process is going well!
4. But then I am trying to launch "git submodule update" and I got an error:
"fatal: not a git repository (or any of the parent directories): .git"

![image](https://user-images.githubusercontent.com/1913784/72975297-a1d13600-3de1-11ea-82cf-c99ebb98e2ee.png)

**Comment by AzatKhafizov** [comment]
I tried to move to AutoLOD folder and repeat "git submodule update" command, and there were no errors.
But in Unity there are the same problems.

ps. I tried to restart Unity, it did not help

**Comment by AzatKhafizov** [comment]
![image](https://user-images.githubusercontent.com/1913784/72975551-1310e900-3de2-11ea-8d53-559f18f66aff.png)

**Comment by AzatKhafizov** [comment]
And yes, AutoLOD/Packages/UnityMeshSimplifier folder is not empty.
But because of Preferences/AutoLOD does not work, I can not configure it

Could you say me, please, is there any other options to get AutoLOD with UnityMeshSimplifier?
I want to test it very much=)
![image](https://user-images.githubusercontent.com/1913784/72975769-6aaf5480-3de2-11ea-9f74-75fc0c47481f.png)

**Comment by FeldNico** [comment]
What I've done was changing `s_Batcher` to `batchers` in line **681** and **685** in AutoLOD.cs

**Comment by AzatKhafizov** [comment]
> What I've done was changing `s_Batcher` to `batchers` in line **681** and **685** in AutoLOD.cs

FeldNico, OH MY GOD!
Thank you sooooo much!
You are great!
![image](https://user-images.githubusercontent.com/1913784/73052669-b02d5980-3e96-11ea-98ad-e45ad4000f8b.png)

**Comment by AzatKhafizov** [comment]
amirebrahimi and FeldNico, right now I am testing AutoLOD.
If everything will be OK, I will close this thread in the nearest time.
If not - I will ask new question

**Comment by AzatKhafizov** [comment]
Well, I think I will create separated thread, because new issue is not connected with Setup, it is connected with User Experience.
Description of the problem: when I use AutoLOD sometimes Unity stops responding. And only first top line of Commands is working (this is the reason, why I can Save my scene safely and safely quit from application)
![image](https://user-images.githubusercontent.com/1913784/73064215-c399ee00-3eb1-11ea-9e4e-ed819bd49889.png)

**Comment by AzatKhafizov** [comment]
https://github.com/Unity-Technologies/AutoLOD/issues/64
Here is description of the new problem.
**amirebrahimi** and **FeldNico**, thank you for your help!
