### ISSUE TITLE
Editor stops responding after Saving scene

### ISSUE THREAD

**Issue by AzatKhafizov** [Unity-Technologies/AutoLOD#64]
Hi everyone!
I want to say again Big thanks to great **amirebrahimi** and **FeldNico** for helping of setup of AutoLOD in new Unity project. If you have such problem, you can check this thread: https://github.com/Unity-Technologies/AutoLOD/issues/63

Unfortunately, after solving of this problem I encountered new issue.
After activating of AutoLOD when I have a lot of objects and when I am saving the scene - sometimes Editor stops responding.
Only top line of Commands is working like File, Edit, Assets, GameObject and so on.

Could you say me, please, how can I fix this problem? Because right now I need to restart Unity almost every 5-10 minutes. It is not convenient.

![image](https://user-images.githubusercontent.com/1913784/73065606-027d7300-3eb5-11ea-8db5-30b96f9d1004.png)

**Comment by amirebrahimi** [comment]
When you say "activating AutoLOD" do you mean SceneLOD perchance?
Usually AutoLOD only is performing work on import of objects.

**Comment by AzatKhafizov** [comment]
Hi!
Yeah, I mean option in Preferences
![image](https://user-images.githubusercontent.com/1913784/73522850-8934d180-441a-11ea-8d7a-636b4577e684.png)

**Comment by amirebrahimi** [comment]
Can you update to latest and see if that fixes your issue? I fixed some SceneLOD issues when I made the tutorial video.

**Comment by AzatKhafizov** [comment]
**amirebrahimi**, yes, of course!
I planned to give you detailed feedback at this weekend on this thread: https://github.com/Unity-Technologies/AutoLOD/issues/65

And also I will check Unity for fixing of freezing.

ps. Sorry for delay - these weeks I am extremely busy.

**Comment by AzatKhafizov** [comment]
Hi, dear **amirebrahimi**!
I checked your fixes, watched your cool video and described what I've done at thread, which is connected with Principle of work of HLOD:
https://github.com/Unity-Technologies/AutoLOD/issues/65#issuecomment-585576882

Unfortunately, when I tested my 30x30 array of spheres without HLOD and with HLOD and then saved the scene - editor stopped responding.
Moreover, I noticed, that I can click on something in the Hierarchy of the scene, then minimize window of application, and then maximize it again - new object will be selected (but Inspector view will not be updated)
So, something strange happens. And, like I said top line of commands is working and it allows me to save scene and quit safely

**Comment by amirebrahimi** [comment]
Hope to take a look at this soon. Apologies it has been so long.

**Comment by AzatKhafizov** [comment]
> Hope to take a look at this soon. Apologies it has been so long.

Thank you!
By the way, version of my editor was 2019.2.17.f1
Does it play an important role, maybe?

In your tutorial video you use 2018.4.16f1

**Comment by AtheosCode** [comment]
same problem in unity  2019.3.9f1

**Comment by amirebrahimi** [comment]
Should be fixed now. Took forever and a day to get back to this @AzatKhafizov.

**Comment by AzatKhafizov** [comment]
> Should be fixed now. Took forever and a day to get back to this @AzatKhafizov.

**amirebrahimi**, thank you very much! I will check it as soon as I will be free!

ps. Sorry for delay with answer - I have a lot of work at my job
