### ISSUE TITLE
No Mesh simplifier Found

### ISSUE THREAD

**Issue by Gui205** [Unity-Technologies/AutoLOD#66]
Hi ! 

I had a problem with AutoLod he don't found any Simplifier, in the past he use Simplygon but i did the update and now i got this problem. 

[https://image.noelshack.com/fichiers/2020/06/1/1580717976-nomeshsimplifier.png](url)

**Comment by amirebrahimi** [comment]
I tried to recreate your problem and although I wasn't able to I tried to make it more robust with 0b0ec53

Could you retry @Gui205 and let me know if you still get the same issue? I'm also wondering if it only happens the first time a user uses AutoLOD (due to EditorPrefs).
