### ISSUE TITLE
No mesh simplifier found in setting when importing project

### ISSUE THREAD

**Issue by ifra1000** [Unity-Technologies/AutoLOD#69]
No mesh simplifier found in setting when importing project and where i get these simplifiers packages which are mentioned and i purchase mesh simplifiy from assetstore so how i connect it with this project

**Comment by amirebrahimi** [comment]
Apologies for not responding sooner. Did you make sure to follow the cloning instructions (w/ submodules) in the [README](../blob/master/README.md#cloning)?

Also, unless the Mesh Simplify asset store package supports AutoLOD, then it would require implementing [IMeshSimplifier](../blob/master/Scripts/Interfaces/IMeshSimplifier.cs) from this project in order to enable support.

**Comment by HoomanJCode** [comment]
> Apologies for not responding sooner. Did you make sure to follow the cloning instructions (w/ submodules) in the [README](../blob/master/README.md#cloning)?
> 
> Also, unless the Mesh Simplify asset store package supports AutoLOD, then it would require implementing [IMeshSimplifier](../blob/master/Scripts/Interfaces/IMeshSimplifier.cs) from this project in order to enable support.

im using git to manage my project and team, i have "AutoLOD: You must set a valid Default Mesh Simplifier under Edit -> Preferences" error on some computers, but my computer is ok. unity 2020.1.0b10

**Comment by HoomanJCode** [comment]
I fixed this on another computer by re cloning package.
here there are some changes on ProjectSettings.asset
![image](https://user-images.githubusercontent.com/50550106/86121156-c3e68700-baea-11ea-964d-31c12ad13628.png)

and I think friends can fix this by adding "UNITY_CCU;ENABLE_UNITYMESHSIMPLIFIER" at end of here for windows and android separately: (unity 2020.1.0b10)

![image](https://user-images.githubusercontent.com/50550106/86121417-32c3e000-baeb-11ea-8ba6-49ac71177d46.png)

 
@ifra1000  test this.

**Comment by amirebrahimi** [comment]
FYI - there is now package manager support that simplifies the workflow of installing. See the README for installation instructions.
