### ISSUE TITLE
No IMeshSimpifiers found!

### ISSUE THREAD

**Issue by aganwenqi** [Unity-Technologies/AutoLOD#70]

**Comment by amirebrahimi** [comment]
Usually, this is because the repository was downloaded as a .zip file or you cloned without grabbing submodules. Please try [these instructions](../blob/master/README.md#cloning) and let me know if that works.

**Comment by aganwenqi** [comment]
Thank you for your answer.Do you have any detailed help documents?Such as Principle of HLOD generation

**Comment by amirebrahimi** [comment]
Here you go: https://github.com/Unity-Technologies/AutoLOD/wiki/Scenelod
