### ISSUE TITLE
Is there any per-LOD settings?

### ISSUE THREAD

**Issue by redwyre** [Unity-Technologies/AutoLOD#72]
I have some meshes that get too decimated at the lowest LOD so I'd like to increase its triangle budget. Is there any way to do this?

**Comment by amirebrahimi** [comment]
Yes. After it has been imported the first time. Just click on the associated asset file that sits next to the model and you can override any settings for that specifically.

**Comment by redwyre** [comment]
I'm specifically looking to change only one LOD, not the whole model (though I don't see what I can do to change the triangle count from the asset file anyway)
![image](https://user-images.githubusercontent.com/431728/87466826-5003bd00-c65a-11ea-8384-f6d23b732e9c.png)

**Comment by amirebrahimi** [comment]
@redwyre - after you import you can then turn off the check box for "Generate on import" and then you can override the individual lods below that should become enabled. Let me know if this works for you.

**Comment by amirebrahimi** [comment]
Closing since there hasn't been any recent activity.
