### ISSUE TITLE
Instructions missing / doesn't work

### ISSUE THREAD

**Issue by Tymski** [Unity-Technologies/AutoLOD#76]
Made a new project and added the autolod, but it only increases the number of tris and batches.
It would be nice to have an instruction on how to use the tool. Is this expected behaviour?

BEFORE ACTIVATING AUTOLOD
![image](https://user-images.githubusercontent.com/8183632/96287961-f73e1a80-0fe2-11eb-888c-f8253518322a.png)

AFTER ACTIVATING AUTOLOD
![image](https://user-images.githubusercontent.com/8183632/96287860-d1b11100-0fe2-11eb-8b2f-af52423738a0.png)

Also there is a grayed out menu with no way of checking why it can't do anything.
![image](https://user-images.githubusercontent.com/8183632/96288350-92cf8b00-0fe3-11eb-8a3b-03918b0ddb7a.png)

When I edit the LOD Group, objects disappear from the scene. WHY?
![image](https://user-images.githubusercontent.com/8183632/96290166-7c76fe80-0fe6-11eb-9390-906334d468b8.png)

Maybe I got the settings wrong?
![image](https://user-images.githubusercontent.com/8183632/96290413-d677c400-0fe6-11eb-9db3-56805230593f.png)

Pls add a short instruction to your asset. Thanks

**Comment by amirebrahimi** [comment]
@Tymski - there is a video I recorded here: http://www.youtube.com/watch?v=EuBeZvzVwrw

**Comment by amirebrahimi** [comment]
Objects disappear when the hierarchical LODs are getting generated in the background.
