### ISSUE TITLE
Fade options do not seem to work.

### ISSUE THREAD

**Issue by HugoCortell** [Unity-Technologies/AutoLOD#78]
I am certain that I must have set something wrong, I have set my auto LOD to crossfade and yet it still has that pop-in effect.

Am I missing something? What should I do to make crossfades "smoother"?

**Comment by amirebrahimi** [comment]
Hi @HugoCortell. To tease out the issue further can you try to see if this is reproducible in a default project in Unity without AutoLOD involved? Please share a video of the issue, too, if possible and the version of Unity you are using.

**Comment by amirebrahimi** [comment]
Closing issue since it has not had any recent activity.
