### ISSUE TITLE
Where can I find the Simplygon plugin?

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#8]
let's try this
https://forum.unity.com/threads/simplygon-login.498501/#post-3352846

**Comment by laurentopia** [comment]
it works and here is the trick: at first username and password will bork, even if the UI works fine, just restart the compute a few times, install and uninstall the plugin and eventually it will work :)

**Comment by amirebrahimi** [comment]
Are you having an issue with the plugin or is this a sticky for people who are unable to find the plugin?

**Comment by laurentopia** [comment]
It's a sticky. It was working.

**Comment by lalaphoon** [comment]
Seems that the Simplygon is only working on windows 10, is there a way to make it work on Mac?

**Comment by amirebrahimi** [comment]
I don't think Simplygon works on mac. You'll likely need to use the default simplifier that is built-in.

**Comment by DataGreed** [comment]
@amirebrahimi where can I find this simplifier? Is it somewhere in Unity itself?

**Comment by amirebrahimi** [comment]
@DataGreed, the simplifier hooks are in this repository, but require you to download the simplygon plugin for Unity. This issue is simply a "sticky", so that you can get the plugin if you are looking to use simplygon. See the original post above.

**Comment by amirebrahimi** [comment]
Closing, since there is nothing more that can be done here, but it is still pinned on the issues page.
