### ISSUE TITLE
Lightmaps

### ISSUE THREAD

**Issue by Ciulama** [Unity-Technologies/AutoLOD#80]
Hi, does this work with lightmaps? will the combined meshes have uv2 copied from the original meshes? (sorry for posting this as an issue, didnt know where else to ask)

**Comment by amirebrahimi** [comment]
Apologies for the late reply. I had to run a test. It looks like uv2s are copied, but the materials are not properly set up (at least with the built-in lightmapper). So, I guess the answer is no, currently.
