### ISSUE TITLE
SimplygonMeshSimplifier generate error!

### ISSUE THREAD

**Issue by STL1024** [Unity-Technologies/AutoLOD#86]
![image](https://user-images.githubusercontent.com/4653311/153138014-0c8edd4e-5687-40be-b68e-83f9e0ececa3.png)

**Comment by STL1024** [comment]
There is a high probability of occurrence

**Comment by amirebrahimi** [comment]
From your stack trace it looks like you are testing with HDRP, which is unsupported. Unfortunately, this project no longer is being actively developed, so unless that changes there will not likely be this additional support.

Simplygon support should work for the built-in renderer though.
