### ISSUE TITLE
Blend shape weight must be greater than previous frame weight

### ISSUE THREAD

**Issue by 1stMan000** [Unity-Technologies/AutoLOD#94]
Getting a failed to generate LODs pop up which states that 'Blend shape weight must be greater than previous frame weight'.
What can be done to fix this?

**Comment by amirebrahimi** [comment]
I no longer maintain this project (I no longer work at Unity), but my suggestion would be to turn off importing blend shapes on the model itself or if you need it on the main LOD0 to make a copy of your model and turn off blend shape importing and use that for LOD1+.

A similar issue in another project: vrm-c/UniVRM#1104

**Comment by 1stMan000** [comment]
yes, your fix worked perfectly. I needed the blend shapes so I had that as LOD0 and copy pasted the same model with no imported shapes. Hope this project is still being worked on, it's a very helpful feature.
